create table categoria (id int8 generated by default as identity, nome varchar(255) not null, primary key (id))

create table categoria_mapping (fabricante_id int8 not null, categoria_id int8 not null)

create table fabricante (id int8 generated by default as identity, nome varchar(255) not null, primary key (id))

create table produto (id int8 generated by default as identity, nome varchar(255) not null, price float8 not null, categoria_id int8, fabricante_id int8, primary key (id))

alter table if exists categoria add constraint UK_prx5elpv558ah8pk8x18u56yc unique (nome)

alter table if exists categoria_mapping add constraint UK_agdv3vo0emtkk1jq85yi5xwyp unique (categoria_id)

alter table if exists fabricante add constraint UK_rrrvrs9jgp19h98brra2y43br unique (nome)

alter table if exists produto add constraint UK_hdot1xprktyi4sf2onvllkmkd unique (nome)

alter table if exists produto add constraint UK_lkoao1x10fitc56nu9eltr9pn unique (price)

alter table if exists categoria_mapping add constraint FK1ddhuaimoteuy842o62rdiujc foreign key (categoria_id) references categoria

alter table if exists categoria_mapping add constraint FKaccjdba27y0le8falsylnxh43 foreign key (fabricante_id) references fabricante

alter table if exists produto add constraint FKopu9jggwnamfv0c8k2ri3kx0a foreign key (categoria_id) references categoria

alter table if exists produto add constraint FKkhet3jcpkstqvj3pcgvmuimtr foreign key (fabricante_id) references fabricante
